### PR TITLE
Support multiple branch backup

### PR DESCRIPTION
**Pull request by callamd**
add `backup.all_branches` option to provide ability to clone all branches of a repo - this actually allows us to save code which may currently be a work in progress. It's also the most likely code to be accidentally deleted.

Set `all_branches = true` under the `[backup]` section to enable the feature.

I didn't add options for enabling this via CLI. This is at least a start!

### CODE REVIEW

**Comment by dllacer** [comment]
Where do we have to add the option `backup.all_branches`??

**Comment by dllacer** [comment]
Is this already added? I mean, the option `backup.all_branches`.

**Comment by cal97g** [comment]
@dllacer see https://github.com/OpenReplyDE/bbbackup/pull/5/files#diff-fffdf61be0127744834e9b9d35baecd7R29

**Comment by dllacer** [comment]
Hi! I have modified the `bbbackup.py` file and the `config` file, but it fails when it performs the if statement `if BACKUP_ALL_BRANCHES:`
The exception is: `Exception: name 'BACKUP_ALL_BRANCHES' is not defined`
Is there anywhere else I have to declare this variable?

**Comment by cal97g** [comment]
It should be defined above. Are you sure you're running on this branch? @dllacer

**Comment by or-staedtler** [comment]
Hey, @dllacer and @cal97g would you like to test the latest version 1.4. build 42? I merged the flag in the config and adopted the logic for the configuration. But I did not yet merge the other parts because from what I understood the `no_single_branch=True` parameter for GitPython should actually resolve the issue successfully and not only backup the master/default branch.

It would help me to get to know if the updated code fits your requirements or if I still need to investigate further how to get the perfect backup-clone of a repo.

**Pull request merged**
